"""actualización de modelos2

Revision ID: 0f9b68c99221
Revises: ef7d0e5400cf
Create Date: 2025-07-20 21:43:52.560077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9b68c99221'
down_revision = 'ef7d0e5400cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False))
        batch_op.drop_constraint(batch_op.f('turnos_rol_operativo_id_fkey'), type_='foreignkey')
        batch_op.drop_column('rol_operativo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol_operativo_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('turnos_rol_operativo_id_fkey'), 'roles_operativos', ['rol_operativo_id'], ['id'])
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
