"""empty message

Revision ID: 250d823da03a
Revises: 473cb0559fe1
Create Date: 2025-07-21 17:20:26.036553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250d823da03a'
down_revision = '473cb0559fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dependencias', schema=None) as batch_op:
        batch_op.alter_column('zona_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('zonas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dependencia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'dependencias', ['dependencia_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zonas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dependencia_id')

    with op.batch_alter_table('dependencias', schema=None) as batch_op:
        batch_op.alter_column('zona_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
