"""empty message

Revision ID: 2ed6a86c314d
Revises: 250d823da03a
Create Date: 2025-07-21 18:27:43.040620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed6a86c314d'
down_revision = '250d823da03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zona_id', sa.Integer(), nullable=True))
        batch_op.alter_column('dependencia_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'zonas', ['zona_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('dependencia_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('zona_id')

    # ### end Alembic commands ###
