"""actualización de modelos3

Revision ID: 473cb0559fe1
Revises: 0f9b68c99221
Create Date: 2025-07-20 21:48:56.446173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '473cb0559fe1'
down_revision = '0f9b68c99221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_inicio', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('hora_fin', sa.Time(), nullable=False))
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('fecha_inicio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('hora_fin')
        batch_op.drop_column('hora_inicio')

    # ### end Alembic commands ###
