"""Migración Inicial

Revision ID: ef7d0e5400cf
Revises: 
Create Date: 2025-07-20 20:20:04.139839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7d0e5400cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dependencias', schema=None) as batch_op:
        batch_op.alter_column('zona_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('guardias', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('licencias', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('solicitudes_cambio', schema=None) as batch_op:
        batch_op.alter_column('usuario_solicitante_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.alter_column('rol_operativo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('dependencia_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('turnos_asignados', schema=None) as batch_op:
        batch_op.alter_column('turno_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grado', sa.String(length=50), nullable=False))
        batch_op.alter_column('dependencia_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('usuarios_roles_operativos', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rol_operativo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('zonas', schema=None) as batch_op:
        batch_op.alter_column('jefatura_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zonas', schema=None) as batch_op:
        batch_op.alter_column('jefatura_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('usuarios_roles_operativos', schema=None) as batch_op:
        batch_op.alter_column('rol_operativo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('dependencia_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('grado')

    with op.batch_alter_table('turnos_asignados', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('turno_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.alter_column('dependencia_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('rol_operativo_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('solicitudes_cambio', schema=None) as batch_op:
        batch_op.alter_column('usuario_solicitante_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('licencias', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('guardias', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('dependencias', schema=None) as batch_op:
        batch_op.alter_column('zona_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
