"""empty message

Revision ID: fef793f13790
Revises: 2ed6a86c314d
Create Date: 2025-07-22 15:51:43.765919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef793f13790'
down_revision = '2ed6a86c314d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turno_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'turnos', ['turno_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('turno_id')

    # ### end Alembic commands ###
